"""Typed dictionaries describing the shared state passed between agents."""

__all__ = ["ResearchState"]
from typing import TypedDict, List, Optional, Dict, Any

class AgentSourceResult(TypedDict, total=False):
    """Raw output from a single agent tool invocation."""
    name: str
    items: List[Any]
    metadata: Dict[str, Any]

class AgentResult(TypedDict, total=False):
    """Container holding an agent's sources plus timing/token metadata."""
    sources: List[AgentSourceResult]
    elapsed: float
    tokens: int
    cost: float
    details: Dict[str, Any]

class ResearchState(TypedDict, total=False):
    """Shared mutable state passed between nodes in the research workflow."""
    topic: str                      # The initial user input
    mode: str                       # Research depth selector
    selected_agents: Optional[List[str]]  # Agents chosen for this run
    domain: Optional[str]                 # Normalized research domain key
    domain_label: Optional[str]           # User-facing domain selection
    perplexity_prompt_path: Optional[str] # Domain-specific prompt for Perplexity
    synthesizer_prompt_path: Optional[str] # Domain-specific prompt for the synthesizer
    research_plan: Optional[str]    # The plan generated by the orchestrator
    web_results: Optional[AgentResult]  # Raw data from web research tools
    academic_results: Optional[AgentResult]  # Raw data from academic sources
    news_results: Optional[AgentResult]  # Raw data from news sources
    social_sentiment: Optional[AgentResult]  # Raw social sentiment data
    financial_data: Optional[AgentResult]    # Raw financial data
    perplexity_results: Optional[AgentResult]  # Mock Perplexity research data
    youtube_results: Optional[AgentResult]    # Mock YouTube research data
    vector_store_result: Optional[AgentResult]  # Vector store status
    rag_result: Optional[AgentResult]          # RAG retrieval output
    cleanup_result: Optional[AgentResult]      # Cleanup agent output
    synthesizer_result: Optional[AgentResult]  # Metrics from the synthesizer agent
    final_report: Optional[str]     # The final compiled report
    archive_path: Optional[str]    # Path to archived JSON snapshot


